/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_role = pgEnum("enum_users_role", ["admin", "editor", "author"]);
export const enum_articles_status = pgEnum("enum_articles_status", [
  "published",
  "draft",
  "archived",
]);
export const enum_comments_status = pgEnum("enum_comments_status", ["approved", "pending", "spam"]);
export const enum_newsletters_status = pgEnum("enum_newsletters_status", [
  "active",
  "unsubscribed",
]);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    role: enum_users_role("role").notNull().default("admin"),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    resetPasswordRequestedAt: timestamp("reset_password_requested_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", { mode: "string", withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const articles = pgTable(
  "articles",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    lead: varchar("lead").notNull(),
    content: varchar("content").notNull(),
    featuredImage: integer("featured_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    featuredImageUrl: varchar("featured_image_url"),
    imageCaption: varchar("image_caption"),
    category: integer("category_id")
      .notNull()
      .references(() => categories.id, {
        onDelete: "set null",
      }),
    author: integer("author_id")
      .notNull()
      .references(() => authors.id, {
        onDelete: "set null",
      }),
    reporter: integer("reporter_id").references(() => users.id, {
      onDelete: "set null",
    }),
    status: enum_articles_status("status").notNull().default("draft"),
    isFeatured: boolean("is_featured").default(false),
    isBreaking: boolean("is_breaking").default(false),
    publishedAt: timestamp("published_at", { mode: "string", withTimezone: true, precision: 3 }),
    readingTimeMinutes: numeric("reading_time_minutes", { mode: "number" }),
    viewCount: numeric("view_count", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("articles_title_idx").on(columns.title),
    uniqueIndex("articles_slug_idx").on(columns.slug),
    index("articles_featured_image_idx").on(columns.featuredImage),
    index("articles_category_idx").on(columns.category),
    index("articles_author_idx").on(columns.author),
    index("articles_reporter_idx").on(columns.reporter),
    index("articles_status_idx").on(columns.status),
    index("articles_updated_at_idx").on(columns.updatedAt),
    index("articles_created_at_idx").on(columns.createdAt),
  ],
);

export const articles_rels = pgTable(
  "articles_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    tagsID: integer("tags_id"),
  },
  (columns) => [
    index("articles_rels_order_idx").on(columns.order),
    index("articles_rels_parent_idx").on(columns.parent),
    index("articles_rels_path_idx").on(columns.path),
    index("articles_rels_tags_id_idx").on(columns.tagsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [articles.id],
      name: "articles_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tagsID"]],
      foreignColumns: [tags.id],
      name: "articles_rels_tags_fk",
    }).onDelete("cascade"),
  ],
);

export const categories = pgTable(
  "categories",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    description: varchar("description"),
    color: varchar("color").default("#2563eb"),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("categories_slug_idx").on(columns.slug),
    index("categories_updated_at_idx").on(columns.updatedAt),
    index("categories_created_at_idx").on(columns.createdAt),
  ],
);

export const authors = pgTable(
  "authors",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    role: varchar("role").notNull().default("Journalist & Editorial Staff"),
    bio: varchar("bio"),
    avatar: varchar("avatar"),
    email: varchar("email"),
    twitter: varchar("twitter"),
    linkedin: varchar("linkedin"),
    user: integer("user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("authors_slug_idx").on(columns.slug),
    uniqueIndex("authors_user_idx").on(columns.user),
    index("authors_updated_at_idx").on(columns.updatedAt),
    index("authors_created_at_idx").on(columns.createdAt),
  ],
);

export const tags = pgTable(
  "tags",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("tags_slug_idx").on(columns.slug),
    index("tags_updated_at_idx").on(columns.updatedAt),
    index("tags_created_at_idx").on(columns.createdAt),
  ],
);

export const comments = pgTable(
  "comments",
  {
    id: serial("id").primaryKey(),
    article: integer("article_id")
      .notNull()
      .references(() => articles.id, {
        onDelete: "set null",
      }),
    name: varchar("name").notNull(),
    email: varchar("email").notNull(),
    content: varchar("content").notNull(),
    status: enum_comments_status("status").notNull().default("pending"),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("comments_article_idx").on(columns.article),
    index("comments_updated_at_idx").on(columns.updatedAt),
    index("comments_created_at_idx").on(columns.createdAt),
  ],
);

export const newsletters = pgTable(
  "newsletters",
  {
    id: serial("id").primaryKey(),
    email: varchar("email").notNull(),
    status: enum_newsletters_status("status").notNull().default("active"),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("newsletters_email_idx").on(columns.email),
    index("newsletters_updated_at_idx").on(columns.updatedAt),
    index("newsletters_created_at_idx").on(columns.createdAt),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    caption: varchar("caption"),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", { mode: "number" }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", { mode: "number" }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_hero_url: varchar("sizes_hero_url"),
    sizes_hero_width: numeric("sizes_hero_width", { mode: "number" }),
    sizes_hero_height: numeric("sizes_hero_height", { mode: "number" }),
    sizes_hero_mimeType: varchar("sizes_hero_mime_type"),
    sizes_hero_filesize: numeric("sizes_hero_filesize", { mode: "number" }),
    sizes_hero_filename: varchar("sizes_hero_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(columns.sizes_card_filename),
    index("media_sizes_hero_sizes_hero_filename_idx").on(columns.sizes_hero_filename),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    articlesID: integer("articles_id"),
    categoriesID: integer("categories_id"),
    authorsID: integer("authors_id"),
    tagsID: integer("tags_id"),
    commentsID: integer("comments_id"),
    newslettersID: integer("newsletters_id"),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_articles_id_idx").on(columns.articlesID),
    index("payload_locked_documents_rels_categories_id_idx").on(columns.categoriesID),
    index("payload_locked_documents_rels_authors_id_idx").on(columns.authorsID),
    index("payload_locked_documents_rels_tags_id_idx").on(columns.tagsID),
    index("payload_locked_documents_rels_comments_id_idx").on(columns.commentsID),
    index("payload_locked_documents_rels_newsletters_id_idx").on(columns.newslettersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["articlesID"]],
      foreignColumns: [articles.id],
      name: "payload_locked_documents_rels_articles_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "payload_locked_documents_rels_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["authorsID"]],
      foreignColumns: [authors.id],
      name: "payload_locked_documents_rels_authors_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tagsID"]],
      foreignColumns: [tags.id],
      name: "payload_locked_documents_rels_tags_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["commentsID"]],
      foreignColumns: [comments.id],
      name: "payload_locked_documents_rels_comments_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["newslettersID"]],
      foreignColumns: [newsletters.id],
      name: "payload_locked_documents_rels_newsletters_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const site_settings = pgTable("site_settings", {
  id: serial("id").primaryKey(),
  siteName: varchar("site_name").notNull().default("Modern News Portal"),
  tagline: varchar("tagline").default("Jurnalisme Terpercaya, Cepat, dan Mendalam"),
  description: varchar("description").default(
    "Portal berita modern yang menyajikan liputan mendalam seputar teknologi, bisnis, sains, dan peristiwa global secara akurat dan independen.",
  ),
  contactEmail: varchar("contact_email").default("redaksi@modernnews.id"),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }),
});

export const breaking_news = pgTable("breaking_news", {
  id: serial("id").primaryKey(),
  isActive: boolean("is_active").default(true),
  headline: varchar("headline").default(
    "Peluncuran Misi Luar Angkasa Generasi Terbaru Berhasil Memasuki Orbit Bumi",
  ),
  url: varchar("url").default("/berita/peluncuran-misi-luar-angkasa-orbit-bumi"),
  badgeText: varchar("badge_text").default("BREAKING"),
  updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }),
  createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }),
});

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: "sessions",
  }),
}));
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_articles_rels = relations(articles_rels, ({ one }) => ({
  parent: one(articles, {
    fields: [articles_rels.parent],
    references: [articles.id],
    relationName: "_rels",
  }),
  tagsID: one(tags, {
    fields: [articles_rels.tagsID],
    references: [tags.id],
    relationName: "tags",
  }),
}));
export const relations_articles = relations(articles, ({ one, many }) => ({
  featuredImage: one(media, {
    fields: [articles.featuredImage],
    references: [media.id],
    relationName: "featuredImage",
  }),
  category: one(categories, {
    fields: [articles.category],
    references: [categories.id],
    relationName: "category",
  }),
  author: one(authors, {
    fields: [articles.author],
    references: [authors.id],
    relationName: "author",
  }),
  reporter: one(users, {
    fields: [articles.reporter],
    references: [users.id],
    relationName: "reporter",
  }),
  _rels: many(articles_rels, {
    relationName: "_rels",
  }),
}));
export const relations_categories = relations(categories, () => ({}));
export const relations_authors = relations(authors, ({ one }) => ({
  user: one(users, {
    fields: [authors.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_tags = relations(tags, () => ({}));
export const relations_comments = relations(comments, ({ one }) => ({
  article: one(articles, {
    fields: [comments.article],
    references: [articles.id],
    relationName: "article",
  }),
}));
export const relations_newsletters = relations(newsletters, () => ({}));
export const relations_media = relations(media, () => ({}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    articlesID: one(articles, {
      fields: [payload_locked_documents_rels.articlesID],
      references: [articles.id],
      relationName: "articles",
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
    authorsID: one(authors, {
      fields: [payload_locked_documents_rels.authorsID],
      references: [authors.id],
      relationName: "authors",
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: "tags",
    }),
    commentsID: one(comments, {
      fields: [payload_locked_documents_rels.commentsID],
      references: [comments.id],
      relationName: "comments",
    }),
    newslettersID: one(newsletters, {
      fields: [payload_locked_documents_rels.newslettersID],
      references: [newsletters.id],
      relationName: "newsletters",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: "_rels",
  }),
}));
export const relations_payload_migrations = relations(payload_migrations, () => ({}));
export const relations_site_settings = relations(site_settings, () => ({}));
export const relations_breaking_news = relations(breaking_news, () => ({}));

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role;
  enum_articles_status: typeof enum_articles_status;
  enum_comments_status: typeof enum_comments_status;
  enum_newsletters_status: typeof enum_newsletters_status;
  users_sessions: typeof users_sessions;
  users: typeof users;
  articles: typeof articles;
  articles_rels: typeof articles_rels;
  categories: typeof categories;
  authors: typeof authors;
  tags: typeof tags;
  comments: typeof comments;
  newsletters: typeof newsletters;
  media: typeof media;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  site_settings: typeof site_settings;
  breaking_news: typeof breaking_news;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_articles_rels: typeof relations_articles_rels;
  relations_articles: typeof relations_articles;
  relations_categories: typeof relations_categories;
  relations_authors: typeof relations_authors;
  relations_tags: typeof relations_tags;
  relations_comments: typeof relations_comments;
  relations_newsletters: typeof relations_newsletters;
  relations_media: typeof relations_media;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_site_settings: typeof relations_site_settings;
  relations_breaking_news: typeof relations_breaking_news;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
